#!/bin/bash

script_dir=$(dirname "$0")

script_name="$1"
script_args="${@:2}"
script_path="${script_dir}/${script_name}.ts"
tsconfig_path="${script_dir}/tsconfig.json"
tsnode_path="./node_modules/.bin/ts-node"

cmd="${tsnode_path} --project ${tsconfig_path} ${script_path} ${script_args}"

main() {
    echo "> ${cmd}"
    eval "${cmd}"
}
main
